# Generated by Django 4.2.3 on 2023-07-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=255)),
                ("job_description", models.TextField(max_length=2000)),
                ("job_requirements", models.TextField(max_length=2000)),
                ("job_responsibilities", models.TextField(max_length=2000)),
            ],
        ),
    ]
