# Generated by Django 4.2.3 on 2023-07-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_description",
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_requirements",
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_responsibilities",
            field=models.TextField(max_length=3000),
        ),
    ]
